npx sb init
starts and loads but then errors:

The requested module '/node_modules/.vite-storybook/deps/@mdx-js_preact.js?v=90b239ca' does not provide an export named 'mdx'
SyntaxError: The requested module '/node_modules/.vite-storybook/deps/@mdx-js_preact.js?v=90b239ca' does not provide an export named 'mdx'